java
Cookie0622/Cookie pull request #1
Opened 2016-11-09 10:02 UTC by Cookie0622

ScoreException can not be thrown,why? How to fix?

2016-12-15 03:39 UTC, ashfaq-sb commented on Custom ScoreException
> +public class ScoreException {
ScoreException class should extend Throwable Class like:
class ScoreException extends Throwable{
....}

2016-12-15 04:18 UTC, ashfaq-sb requested changes
Let me fix it

2016-12-15 15:58 UTC, ashfaq-sb approved these changes

2016-12-15 15:58 UTC, ashfaq-sb commented on Custom ScoreException
> +public class ScoreException {
`class ScoreException extends Throwable{`
....`}`

2016-12-15 15:58 UTC, ashfaq-sb commented on Custom ScoreException
> +			s1.score=-4;
`s1.score(-4);`

2016-12-21 06:17 UTC, Cookie0622 commented on Custom ScoreException
> +			s1.score=-4;
appreciate you dude

2017-01-03 17:45 UTC, ashfaq-sb commented on Custom ScoreException
> +			s1.score=-4;
Have you managed to correct it?

2017-01-03 17:45 UTC, ashfaq-sb commented on Custom ScoreException
> +			s1.score=-4;
Have you managed to correct it?

2017-01-05 04:21 UTC, Cookie0622 commented
Yes
----- 原始邮件 -----
发件人：Muhammad Ashfaq <notifications@github.com>
收件人：Cookie0622/Cookie <Cookie@noreply.github.com>
抄送人：Cookie0622 <cookie_8421@sina.cn>,  Author <author@noreply.github.com>
主题：Re: [Cookie0622/Cookie] java (#1)
日期：2017年01月04日 01点45分

@ashfaq-sb commented on this pull request.



In Custom ScoreException:
> +}
+public class ScoreException {
+	String message;
+	public ScoreException(int s){
+		message = "Enter is invalid";
+	}
+	public String warnMess(){
+		return message;
+	}
+
+}
+public class TestScore {
+	public static void main(String []args){
+		Score s1 = new Score();
+		try{
+			s1.score=-4;

Have you managed to correct it?

&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2023-08-19 05:26 UTC, merged